import { defineBooks } from "@/config/media/define-catalog";

export const books = defineBooks([
  {
    id: "the-story-of-the-human-body",
    title: "The Story of the Human Body",
    authors: ["Daniel E. Lieberman"],
    summary:
      "An evolutionary account of the human body and why ancient adaptations can conflict with modern environments, producing many chronic diseases.",
    releaseYear: 2013,
    genres: ["Science", "Human Evolution", "Health"],
    publisher: "Penguin Books",
    pageCount: 480,
    isbn13: "9780141399959",
    href: "https://openlibrary.org/isbn/9780141399959",
    sourceId: "OL21084943W",
    artwork: ["https://covers.openlibrary.org/b/id/12626418-L.jpg", 312, 500],
  },
  {
    id: "1776",
    title: "1776",
    authors: ["David McCullough"],
    summary:
      "A narrative history of the American Revolution's pivotal first year, centered on George Washington, the Continental Army, and the British forces opposing them.",
    releaseYear: 2005,
    genres: ["History", "American Revolution", "Biography"],
    publisher: "Simon & Schuster",
    pageCount: 386,
    isbn13: "9780743226714",
    href: "https://openlibrary.org/isbn/9780743226714",
    sourceId: "OL2820748W",
    artwork: ["https://covers.openlibrary.org/b/id/6619411-L.jpg", 325, 500],
  },
  {
    id: "narrative-of-frederick-douglass",
    title: "Narrative of the Life of Frederick Douglass",
    authors: ["Frederick Douglass"],
    summary:
      "Douglass recounts his enslavement, pursuit of literacy, resistance, and escape while exposing the violence and contradictions of American slavery.",
    releaseYear: 1845,
    genres: ["Autobiography", "History", "Abolition"],
    publisher: "Penguin Books",
    pageCount: 159,
    isbn13: "9780140390124",
    href: "https://openlibrary.org/isbn/9780140390124",
    sourceId: "OL69178W",
    artwork: ["https://covers.openlibrary.org/b/id/6942299-L.jpg", 316, 500],
  },
  {
    id: "the-history-of-money",
    title: "The History of Money",
    authors: ["Jack Weatherford"],
    summary:
      "An anthropological history of how currency evolved from barter and coins into banking, credit, and the global financial system.",
    releaseYear: 1997,
    genres: ["Economics", "History", "Anthropology"],
    publisher: "Three Rivers Press",
    pageCount: 304,
    isbn13: "9780609801727",
    href: "https://openlibrary.org/isbn/9780609801727",
    sourceId: "OL8162624W",
    artwork: ["https://covers.openlibrary.org/b/id/390985-L.jpg", 314, 475],
  },
  {
    id: "autobiography-of-benjamin-franklin",
    title: "The Autobiography of Benjamin Franklin",
    authors: ["Benjamin Franklin"],
    summary:
      "Franklin traces his rise from apprentice printer to public figure through experiments in self-improvement, work, civic life, and practical philosophy.",
    releaseYear: 1791,
    genres: ["Autobiography", "American History", "Philosophy"],
    publisher: "ARC Manor",
    pageCount: 205,
    isbn13: "9781604501841",
    href: "https://openlibrary.org/isbn/9781604501841",
    sourceId: "OL26492W",
    artwork: ["https://covers.openlibrary.org/b/id/10731492-L.jpg", 330, 500],
  },
  {
    id: "why-we-sleep",
    title: "Why We Sleep",
    authors: ["Matthew Walker"],
    summary:
      "A survey of sleep science covering how sleep shapes memory, emotion, metabolism, immunity, and the health costs of chronic deprivation.",
    releaseYear: 2017,
    genres: ["Science", "Sleep", "Health"],
    publisher: "Scribner",
    pageCount: 360,
    isbn13: "9781501144318",
    href: "https://openlibrary.org/isbn/9781501144318",
    sourceId: "OL20168133W",
    artwork: ["https://covers.openlibrary.org/b/id/15208018-L.jpg", 331, 500],
  },
  {
    id: "genghis-khan-and-the-making-of-the-modern-world",
    title: "Genghis Khan and the Making of the Modern World",
    authors: ["Jack Weatherford"],
    summary:
      "A reassessment of Genghis Khan and the Mongol Empire's role in expanding trade, diplomacy, law, and cultural exchange across Eurasia.",
    releaseYear: 2004,
    genres: ["History", "Biography", "Mongol Empire"],
    publisher: "Crown",
    pageCount: 312,
    isbn13: "9780609809648",
    href: "https://openlibrary.org/isbn/9780609809648",
    sourceId: "OL8162628W",
    artwork: ["https://covers.openlibrary.org/b/id/390818-L.jpg", 317, 475],
  },
  {
    id: "when-breath-becomes-air",
    title: "When Breath Becomes Air",
    authors: ["Paul Kalanithi"],
    summary:
      "A neurosurgeon facing terminal lung cancer reflects on medicine, identity, mortality, and what makes a life meaningful.",
    releaseYear: 2016,
    genres: ["Memoir", "Medicine", "Mortality"],
    publisher: "Random House",
    pageCount: 256,
    isbn13: "9780812988406",
    href: "https://openlibrary.org/isbn/9780812988406",
    sourceId: "OL17356252W",
    artwork: ["https://covers.openlibrary.org/b/id/12390254-L.jpg", 293, 432],
  },
  {
    id: "the-man-who-mistook-his-wife-for-a-hat",
    title: "The Man Who Mistook His Wife for a Hat",
    authors: ["Oliver Sacks"],
    summary:
      "Clinical case studies of unusual neurological conditions that reveal how perception, memory, language, and identity shape a person's world.",
    releaseYear: 1985,
    genres: ["Neurology", "Psychology", "Case Studies"],
    publisher: "Simon & Schuster",
    pageCount: 243,
    isbn13: "9780684853949",
    href: "https://openlibrary.org/isbn/9780684853949",
    sourceId: "OL1811898W",
    artwork: ["https://covers.openlibrary.org/b/id/10104616-L.jpg", 318, 500],
  },
  {
    id: "mountains-beyond-mountains",
    title: "Mountains Beyond Mountains",
    authors: ["Tracy Kidder"],
    summary:
      "A portrait of physician Paul Farmer's work against infectious disease in Haiti and his challenge to the assumptions behind global health inequality.",
    releaseYear: 2003,
    genres: ["Biography", "Global Health", "Social Justice"],
    publisher: "Random House Trade Paperbacks",
    pageCount: 336,
    isbn13: "9780812973013",
    href: "https://openlibrary.org/isbn/9780812973013",
    sourceId: "OL98216W",
    artwork: ["https://covers.openlibrary.org/b/id/606360-L.jpg", 324, 500],
  },
  {
    id: "waking-up",
    title: "Waking Up",
    authors: ["Sam Harris"],
    summary:
      "A secular exploration of meditation, consciousness, and spiritual experience that separates contemplative practice from religious belief.",
    releaseYear: 2014,
    genres: ["Philosophy", "Meditation", "Consciousness"],
    publisher: "Simon & Schuster",
    pageCount: 256,
    isbn13: "9781451636024",
    href: "https://openlibrary.org/isbn/9781451636024",
    sourceId: "OL17068760W",
    artwork: ["https://covers.openlibrary.org/b/id/10829925-L.jpg", 324, 500],
  },
  {
    id: "the-souls-of-black-folk",
    title: "The Souls of Black Folk",
    authors: ["W. E. B. Du Bois"],
    summary:
      "Essays on Black life after emancipation that introduce double consciousness and examine education, citizenship, culture, and the color line.",
    releaseYear: 1903,
    genres: ["Essays", "Sociology", "African American History"],
    publisher: "Penguin Books",
    pageCount: 247,
    isbn13: "9780140189988",
    href: "https://openlibrary.org/isbn/9780140189988",
    sourceId: "OL28577W",
    artwork: ["https://covers.openlibrary.org/b/id/6564090-L.jpg", 277, 500],
  },
  {
    id: "walden",
    title: "Walden",
    authors: ["Henry David Thoreau"],
    summary:
      "Thoreau's account of living beside Walden Pond uses nature and deliberate simplicity to question work, consumption, society, and freedom.",
    releaseYear: 1854,
    genres: ["Nature Writing", "Philosophy", "Memoir"],
    publisher: "Penguin Books",
    pageCount: 431,
    isbn13: "9780140390445",
    href: "https://openlibrary.org/isbn/9780140390445",
    sourceId: "OL55649W",
    artwork: ["https://covers.openlibrary.org/b/id/11025288-L.jpg", 302, 500],
  },
  {
    id: "mans-search-for-meaning",
    title: "Man's Search for Meaning",
    authors: ["Viktor E. Frankl"],
    summary:
      "Frankl combines his concentration-camp memoir with an introduction to logotherapy and the human capacity to find meaning through suffering.",
    releaseYear: 1946,
    genres: ["Memoir", "Psychology", "Philosophy"],
    publisher: "Beacon Press",
    pageCount: 165,
    isbn13: "9780807014295",
    href: "https://openlibrary.org/isbn/9780807014295",
    sourceId: "OL1268413W",
    artwork: ["https://covers.openlibrary.org/b/id/8513458-L.jpg", 302, 500],
  },
  {
    id: "delivering-happiness",
    title: "Delivering Happiness",
    authors: ["Tony Hsieh"],
    summary:
      "Tony Hsieh explains how Zappos made customer service and company culture operating principles rather than slogans while scaling the business.",
    releaseYear: 2010,
    genres: ["Business", "Leadership", "Company Culture"],
    publisher: "Business Plus",
    pageCount: 253,
    isbn13: "9780446563048",
    href: "https://openlibrary.org/isbn/9780446563048",
    sourceId: "OL15582623W",
    artwork: ["https://covers.openlibrary.org/b/id/6450379-L.jpg", 183, 280],
  },
]);
