import type { MovieMediaShelfItem } from "@/config/media/types";

export const movies = [
  {
    id: "the-two-popes",
    kind: "movie",
    title: "The Two Popes",
    creator: "Fernando Meirelles",
    directors: ["Fernando Meirelles"],
    summary:
      "An imagined series of private conversations between Pope Benedict XVI and the future Pope Francis as the church faces scandal and change.",
    releaseYear: 2019,
    releaseDate: "2019-11-27",
    genres: ["Drama", "History"],
    runtimeMinutes: 125,
    href: "https://www.themoviedb.org/movie/551332-the-two-popes",
    sourceId: "551332",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/4d4mTSfDIFIbUbMLUfaKodvxYXA.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "the-perks-of-being-a-wallflower",
    kind: "movie",
    title: "The Perks of Being a Wallflower",
    creator: "Stephen Chbosky",
    directors: ["Stephen Chbosky"],
    summary:
      "A withdrawn high-school freshman finds friendship and belonging while confronting the trauma and mental-health struggles he has kept buried.",
    releaseYear: 2012,
    releaseDate: "2012-09-20",
    genres: ["Drama", "Coming of Age"],
    runtimeMinutes: 103,
    href: "https://www.themoviedb.org/movie/84892-the-perks-of-being-a-wallflower",
    sourceId: "84892",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/aKCvdFFF5n80P2VdS7d8YBwbCjh.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "dune-2021",
    kind: "movie",
    title: "Dune",
    creator: "Denis Villeneuve",
    directors: ["Denis Villeneuve"],
    summary:
      "Paul Atreides enters a conflict over Arrakis, the desert planet whose spice controls interstellar travel and the balance of imperial power.",
    releaseYear: 2021,
    releaseDate: "2021-09-15",
    genres: ["Science Fiction", "Adventure"],
    runtimeMinutes: 155,
    href: "https://www.themoviedb.org/movie/438631-dune",
    sourceId: "438631",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "your-name",
    kind: "movie",
    title: "Your Name.",
    creator: "Makoto Shinkai",
    directors: ["Makoto Shinkai"],
    summary:
      "Two teenagers begin swapping bodies across distance and time, then race to understand their connection before a disaster separates them permanently.",
    releaseYear: 2016,
    releaseDate: "2016-08-26",
    genres: ["Animation", "Romance", "Drama"],
    runtimeMinutes: 106,
    href: "https://www.themoviedb.org/movie/372058-your-name",
    sourceId: "372058",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "there-will-be-blood",
    kind: "movie",
    title: "There Will Be Blood",
    creator: "Paul Thomas Anderson",
    directors: ["Paul Thomas Anderson"],
    summary:
      "An oilman's ambition turns a California drilling boom into a study of greed, faith, family, and the cost of absolute self-reliance.",
    releaseYear: 2007,
    releaseDate: "2007-12-26",
    genres: ["Drama", "Historical"],
    runtimeMinutes: 158,
    href: "https://www.themoviedb.org/movie/7345-there-will-be-blood",
    sourceId: "7345",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "lost-in-translation",
    kind: "movie",
    title: "Lost in Translation",
    creator: "Sofia Coppola",
    directors: ["Sofia Coppola"],
    summary:
      "Two isolated Americans form an intimate, temporary friendship while drifting through unfamiliar lives and sleepless nights in Tokyo.",
    releaseYear: 2003,
    releaseDate: "2003-09-18",
    genres: ["Drama", "Comedy", "Romance"],
    runtimeMinutes: 102,
    href: "https://www.themoviedb.org/movie/153-lost-in-translation",
    sourceId: "153",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/3jCLmYDIIiSMPujbwygNpqdpM8N.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "iron-man-2008",
    kind: "movie",
    title: "Iron Man",
    creator: "Jon Favreau",
    directors: ["Jon Favreau"],
    summary:
      "After captivity exposes the human cost of his weapons business, Tony Stark builds an armored suit and turns his engineering against his own legacy.",
    releaseYear: 2008,
    releaseDate: "2008-04-30",
    genres: ["Action", "Science Fiction", "Adventure"],
    runtimeMinutes: 126,
    href: "https://www.themoviedb.org/movie/1726-iron-man",
    sourceId: "1726",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "interstellar",
    kind: "movie",
    title: "Interstellar",
    creator: "Christopher Nolan",
    directors: ["Christopher Nolan"],
    summary:
      "As Earth becomes uninhabitable, a team crosses a wormhole in search of a future for humanity while time pulls one family apart.",
    releaseYear: 2014,
    releaseDate: "2014-11-05",
    genres: ["Science Fiction", "Adventure", "Drama"],
    runtimeMinutes: 169,
    href: "https://www.themoviedb.org/movie/157336-interstellar",
    sourceId: "157336",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "inglourious-basterds",
    kind: "movie",
    title: "Inglourious Basterds",
    creator: "Quentin Tarantino",
    directors: ["Quentin Tarantino"],
    summary:
      "A revenge plot, a covert Allied unit, and Nazi leadership converge at a Paris film premiere in an alternate version of World War II.",
    releaseYear: 2009,
    releaseDate: "2009-08-02",
    genres: ["War", "Drama", "Thriller"],
    runtimeMinutes: 153,
    href: "https://www.themoviedb.org/movie/16869-inglourious-basterds",
    sourceId: "16869",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/aupnPtagH9JVBuMrGEanf4iqXEQ.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "prometheus",
    kind: "movie",
    title: "Prometheus",
    creator: "Ridley Scott",
    directors: ["Ridley Scott"],
    summary:
      "A scientific expedition follows ancient clues to humanity's origins and discovers that its possible creators may be a threat rather than an answer.",
    releaseYear: 2012,
    releaseDate: "2012-05-30",
    genres: ["Science Fiction", "Mystery", "Horror"],
    runtimeMinutes: 124,
    href: "https://www.themoviedb.org/movie/70981-prometheus",
    sourceId: "70981",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/qsYQflQhOuhDpQ0W2aOcwqgDAeI.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "free-solo",
    kind: "movie",
    title: "Free Solo",
    creator: "Elizabeth Chai Vasarhelyi and Jimmy Chin",
    directors: ["Elizabeth Chai Vasarhelyi", "Jimmy Chin"],
    summary:
      "A documentary following Alex Honnold's preparation for a ropeless ascent of El Capitan and the physical and emotional stakes surrounding it.",
    releaseYear: 2018,
    releaseDate: "2018-09-28",
    genres: ["Documentary", "Adventure", "Climbing"],
    runtimeMinutes: 100,
    href: "https://www.themoviedb.org/movie/515042-free-solo",
    sourceId: "515042",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "wall-e",
    kind: "movie",
    title: "WALL-E",
    creator: "Andrew Stanton",
    directors: ["Andrew Stanton"],
    summary:
      "A solitary cleanup robot leaves an abandoned Earth after meeting EVE and helps humanity rediscover responsibility, curiosity, and home.",
    releaseYear: 2008,
    releaseDate: "2008-06-26",
    genres: ["Animation", "Science Fiction", "Family"],
    runtimeMinutes: 98,
    href: "https://www.themoviedb.org/movie/10681-wall-e",
    sourceId: "10681",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "catch-me-if-you-can",
    kind: "movie",
    title: "Catch Me If You Can",
    creator: "Steven Spielberg",
    directors: ["Steven Spielberg"],
    summary:
      "A gifted teenage con artist impersonates professionals and forges checks while an FBI agent turns their pursuit into a long-running duel.",
    releaseYear: 2002,
    releaseDate: "2002-12-16",
    genres: ["Crime", "Drama", "Biography"],
    runtimeMinutes: 141,
    href: "https://www.themoviedb.org/movie/640-catch-me-if-you-can",
    sourceId: "640",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/ctjEj2xM32OvBXCq8zAdK3ZrsAj.jpg",
      width: 500,
      height: 750,
    },
  },
  {
    id: "fargo-1996",
    kind: "movie",
    title: "Fargo",
    creator: "Joel Coen and Ethan Coen",
    directors: ["Joel Coen", "Ethan Coen"],
    summary:
      "A desperate car salesman's staged kidnapping unravels into violence while a quietly persistent Minnesota police chief follows the evidence.",
    releaseYear: 1996,
    releaseDate: "1996-03-08",
    genres: ["Crime", "Drama", "Thriller"],
    runtimeMinutes: 98,
    href: "https://www.themoviedb.org/movie/275-fargo",
    sourceId: "275",
    artwork: {
      src: "https://media.themoviedb.org/t/p/w500/rt7cpEr1uP6RTZykBFhBTcRaKvG.jpg",
      width: 500,
      height: 750,
    },
  },
] as const satisfies readonly MovieMediaShelfItem[];
