import type { TvShowMediaShelfItem } from "@/config/media/types";

export const tvShows = [
  {
    id: "avatar-the-last-airbender",
    kind: "tv-show",
    title: "Avatar: The Last Airbender",
    creator: "Michael Dante DiMartino and Bryan Konietzko",
    creators: ["Michael Dante DiMartino", "Bryan Konietzko"],
    summary:
      "The last surviving Airbender learns to master four elements while he and his friends try to end the Fire Nation's century-long war.",
    releaseYear: 2005,
    releaseDate: "2005-02-21",
    endYear: 2008,
    genres: ["Animation", "Adventure", "Fantasy"],
    network: "Nickelodeon",
    format: "animated series",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 30,
    imdbId: "tt0417299",
    href: "https://www.tvmaze.com/shows/555/avatar-the-last-airbender",
    sourceId: "555",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/79/199224.jpg",
      width: 680,
      height: 1000,
    },
  },
  {
    id: "startup",
    kind: "tv-show",
    title: "StartUp",
    creator: "Ben Ketai",
    creators: ["Ben Ketai"],
    summary:
      "A programmer, a financier, and a Haitian-American gang leader build a cryptocurrency startup with dirty money while a corrupt FBI agent closes in.",
    releaseYear: 2016,
    releaseDate: "2016-09-06",
    endYear: 2018,
    genres: ["Crime", "Drama", "Thriller"],
    network: "Crackle",
    format: "series",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 54,
    imdbId: "tt5028002",
    href: "https://www.tvmaze.com/shows/12323/startup",
    sourceId: "12323",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/173/433460.jpg",
      width: 1405,
      height: 2083,
    },
  },
  {
    id: "alien-earth",
    kind: "tv-show",
    title: "Alien: Earth",
    creator: "Noah Hawley",
    creators: ["Noah Hawley"],
    summary:
      "A research vessel crashes on Earth carrying lethal extraterrestrial specimens, drawing a synthetic young woman and a tactical team into the threat.",
    releaseYear: 2025,
    releaseDate: "2025-08-12",
    genres: ["Science Fiction", "Horror", "Thriller"],
    network: "Hulu",
    format: "series",
    language: "English",
    country: "United States",
    status: "running",
    runtimeMinutes: 79,
    imdbId: "tt13623632",
    href: "https://www.tvmaze.com/shows/52336/alien-earth",
    sourceId: "52336",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466409.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "for-all-mankind",
    kind: "tv-show",
    title: "For All Mankind",
    creator: "Ronald D. Moore, Matt Wolpert, and Ben Nedivi",
    creators: ["Ronald D. Moore", "Matt Wolpert", "Ben Nedivi"],
    summary:
      "An alternate history begins with the Soviet Union reaching the Moon first and follows the astronauts, engineers, and families of an unending space race.",
    releaseYear: 2019,
    releaseDate: "2019-11-01",
    genres: ["Drama", "Science Fiction", "Alternate History"],
    network: "Apple TV",
    format: "series",
    language: "English",
    country: "United States",
    status: "running",
    runtimeMinutes: 59,
    imdbId: "tt7772588",
    href: "https://www.tvmaze.com/shows/41414/for-all-mankind",
    sourceId: "41414",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/616/1541416.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "the-diplomat",
    kind: "tv-show",
    title: "The Diplomat",
    creator: "Debora Cahn",
    creators: ["Debora Cahn"],
    summary:
      "A career diplomat becomes the U.S. ambassador to the United Kingdom during an international crisis while her marriage and political future destabilize.",
    releaseYear: 2023,
    releaseDate: "2023-04-20",
    genres: ["Drama", "Political", "Thriller"],
    network: "Netflix",
    format: "series",
    language: "English",
    country: "United States",
    status: "running",
    runtimeMinutes: 49,
    imdbId: "tt17491088",
    href: "https://www.tvmaze.com/shows/60213/the-diplomat",
    sourceId: "60213",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/589/1473527.jpg",
      width: 1000,
      height: 1481,
    },
  },
  {
    id: "foundation",
    kind: "tv-show",
    title: "Foundation",
    creator: "David S. Goyer and Josh Friedman",
    creators: ["David S. Goyer", "Josh Friedman"],
    summary:
      "A mathematician predicts the Galactic Empire's collapse and sends a group of exiles to preserve knowledge and shorten the dark age that will follow.",
    releaseYear: 2021,
    releaseDate: "2021-09-24",
    genres: ["Science Fiction", "Drama", "Mystery"],
    network: "Apple TV",
    format: "series",
    language: "English",
    country: "United States",
    status: "running",
    runtimeMinutes: 53,
    imdbId: "tt0804484",
    href: "https://www.tvmaze.com/shows/35951/foundation",
    sourceId: "35951",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/573/1433544.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "slow-horses",
    kind: "tv-show",
    title: "Slow Horses",
    creator: "Will Smith",
    creators: ["Will Smith"],
    summary:
      "Disgraced MI5 agents assigned to Slough House keep finding their way into active threats under the abrasive leadership of Jackson Lamb.",
    releaseYear: 2022,
    releaseDate: "2022-04-01",
    genres: ["Espionage", "Drama", "Thriller"],
    network: "Apple TV",
    format: "series",
    language: "English",
    country: "United Kingdom",
    status: "running",
    runtimeMinutes: 46,
    imdbId: "tt5875444",
    href: "https://www.tvmaze.com/shows/45039/slow-horses",
    sourceId: "45039",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/593/1484384.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "andor",
    kind: "tv-show",
    title: "Andor",
    creator: "Tony Gilroy",
    creators: ["Tony Gilroy"],
    summary:
      "Cassian Andor's path from detached survivor to committed rebel unfolds alongside the people and institutions building resistance to the Empire.",
    releaseYear: 2022,
    releaseDate: "2022-09-21",
    endYear: 2025,
    genres: ["Science Fiction", "Espionage", "Thriller"],
    network: "Disney+",
    format: "series",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 48,
    imdbId: "tt9253284",
    href: "https://www.tvmaze.com/shows/52341/andor",
    sourceId: "52341",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/564/1411766.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "dexter",
    kind: "tv-show",
    title: "Dexter",
    creator: "James Manos Jr.",
    creators: ["James Manos Jr."],
    summary:
      "A Miami blood-spatter analyst hides a second life as a serial killer who follows a code directing his violence toward other murderers.",
    releaseYear: 2006,
    releaseDate: "2006-10-01",
    endYear: 2013,
    genres: ["Crime", "Drama", "Mystery"],
    network: "Showtime",
    format: "series",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 60,
    imdbId: "tt0773262",
    href: "https://www.tvmaze.com/shows/161/dexter",
    sourceId: "161",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/498/1246067.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "the-blacklist",
    kind: "tv-show",
    title: "The Blacklist",
    creator: "Jon Bokenkamp",
    creators: ["Jon Bokenkamp"],
    summary:
      "A notorious criminal surrenders to the FBI and offers access to dangerous targets, but insists on working only with a newly assigned profiler.",
    releaseYear: 2013,
    releaseDate: "2013-09-23",
    endYear: 2023,
    genres: ["Crime", "Drama", "Thriller"],
    network: "NBC",
    format: "series",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 60,
    imdbId: "tt2741602",
    href: "https://www.tvmaze.com/shows/69/the-blacklist",
    sourceId: "69",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/445/1113538.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "mindhunter",
    kind: "tv-show",
    title: "Mindhunter",
    creator: "Joe Penhall",
    creators: ["Joe Penhall"],
    summary:
      "FBI agents interview imprisoned serial killers and turn those conversations into an early system for behavioral profiling.",
    releaseYear: 2017,
    releaseDate: "2017-10-13",
    endYear: 2019,
    genres: ["Crime", "Drama", "Thriller"],
    network: "Netflix",
    format: "series",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 54,
    imdbId: "tt5290382",
    href: "https://www.tvmaze.com/shows/10822/mindhunter",
    sourceId: "10822",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253490.jpg",
      width: 1790,
      height: 2500,
    },
  },
  {
    id: "the-spy",
    kind: "tv-show",
    title: "The Spy",
    creator: "Gideon Raff",
    creators: ["Gideon Raff"],
    summary:
      "Israeli agent Eli Cohen builds a deep-cover identity inside Syrian political society, gaining influence while the risk to him and his family escalates.",
    releaseYear: 2019,
    releaseDate: "2019-09-06",
    endYear: 2019,
    genres: ["Espionage", "Drama", "Thriller"],
    network: "Netflix",
    format: "miniseries",
    language: "English",
    country: "France",
    status: "ended",
    runtimeMinutes: 54,
    imdbId: "tt5952634",
    href: "https://www.tvmaze.com/shows/35968/the-spy",
    sourceId: "35968",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/209/523364.jpg",
      width: 1500,
      height: 2222,
    },
  },
  {
    id: "the-expanse",
    kind: "tv-show",
    title: "The Expanse",
    creator: "Mark Fergus and Hawk Ostby",
    creators: ["Mark Fergus", "Hawk Ostby"],
    summary:
      "A missing-person case and a stranded ship crew expose a conspiracy capable of destabilizing Earth, Mars, and the settlements of the asteroid belt.",
    releaseYear: 2015,
    releaseDate: "2015-12-14",
    endYear: 2022,
    genres: ["Science Fiction", "Thriller", "Mystery"],
    network: "Syfy and Prime Video",
    format: "series",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 55,
    imdbId: "tt3230854",
    href: "https://www.tvmaze.com/shows/1825/the-expanse",
    sourceId: "1825",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/445/1114081.jpg",
      width: 2000,
      height: 3000,
    },
  },
  {
    id: "masters-of-the-air",
    kind: "tv-show",
    title: "Masters of the Air",
    creator: "John Shiban and John Orloff",
    creators: ["John Shiban", "John Orloff"],
    summary:
      "The airmen of the 100th Bomb Group conduct high-altitude raids over Nazi-occupied Europe and bear the physical and psychological cost of the campaign.",
    releaseYear: 2024,
    releaseDate: "2024-01-26",
    endYear: 2024,
    genres: ["War", "Drama", "History"],
    network: "Apple TV",
    format: "miniseries",
    language: "English",
    country: "United States",
    status: "ended",
    runtimeMinutes: 57,
    imdbId: "tt2640044",
    href: "https://www.tvmaze.com/shows/44388/masters-of-the-air",
    sourceId: "44388",
    artwork: {
      src: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253902.jpg",
      width: 2030,
      height: 3000,
    },
  },
] as const satisfies readonly TvShowMediaShelfItem[];
